"""
Exception Handling
try:


except:
"""
# try:
#     a = [21, 65, 32, 45]
#     print(a[10])
#     print("Hello world")
# except:
#     print("Some error occurred")

# try:
#     a = int(input("Enter number 1: "))
#     b = int(input("Enter number 2: "))
#     print(a / b)
# except Exception as e:
#     print(e)
#     print("Some error occurred")

# try:
#     a = int(input("Enter number 1: "))
#     b = int(input("Enter number 2: "))
#     print(a / b)
# except ZeroDivisionError:
#     print("Cannot divide by zero")
# except ValueError:
#     print("Please input proper integers")
# except:
#     print("Some error occurred")
# else:
#     print("All Good!")
# finally:
#     print("Finally completed")

# try:
#     age = int(input("Enter your age: "))
#     if age >= 18:
#         print("You can vote")
#     else:
#         raise Exception("You cannot vote")
# except Exception as e:
#     print(e)

# try:
#     age = int(input("Enter your age: "))
#     if age < 18:
#         print("You cannot vote")
# except Exception as e:
#     print(e)
# else:
#     print("You can vote")

# try:
#     a = int(input("Enter a number: "))
#     if a % 5 != 0:
#         raise Exception("It is not divisible by 5")

# except ValueError:
#     print("Please input proper integers")


# except Exception as e:
#     print(e)

# else:
#     print("It is divisible by 5")
